#!/usr/bin/perl -w
if ($msg =~ /^!\w* -help(?: (.*))?/){
    if (!$1 || $1 =~ /-?help/ ) {
        return "Fetches a random Chuck Norris \"Joke\"\nUsage: !norris"
	}
}
use HTML::Entities;

if ($msg =~ /^!obama/){
    $url = "Http://www.change.gov";
    print "Fetching: $url\n";
    $ua = LWP::UserAgent->new();
    $ua->default_header("Accept-Encoding" => "gzip, deflate"); 
    $request = HTTP::Request->new(GET => $url);
    $ua->agent('Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.8) Gecko/20051111 Firefox/1.5 BAVM/1.0.0');
    $response = $ua->request($request);
    if ($response->is_success) {
	$contents = $response->decoded_content;
print $contents;
	$i = 0;	
	while ($contents =~ s/id="countdownDaysleft">[\s\S]*?(\d+ Days.*)//) {
	    $norrisfact = $1;	
	    $norrisfact = decode_entities($norrisfact);
	    print "$norrisfact\n";
	}
	return $norrisfact;
    }
}
